package general

// Code generated by avro/gen. DO NOT EDIT.

// Meta is a generated struct.
type Meta struct {
	EventName     string `avro:"event_name"`
	EventID       string `avro:"event_id"`
	EventVersion  string `avro:"event_version"`
	EventProducer string `avro:"event_producer"`
}
