package v1

// Code generated by avro/gen. DO NOT EDIT.

import (
	"time"
)

// AccountCreated is a generated struct.
type AccountCreated struct {
	UserID string `avro:"user_id"`
	Role   string `avro:"role"`
}

// AccountUpdated is a generated struct.
type AccountUpdated struct {
	UserID string `avro:"user_id"`
	Active bool   `avro:"active"`
	Role   string `avro:"role"`
}

// PaymentMade is a generated struct.
type PaymentMade struct {
	UserID      string    `avro:"user_id"`
	Amount      int       `avro:"amount"`
	ProcessedAt time.Time `avro:"processed_at"`
}

// Task is a generated struct.
type Task struct {
	TaskID      string    `avro:"task_id"`
	UserID      string    `avro:"user_id"`
	Description string    `avro:"description"`
	Completed   bool      `avro:"completed"`
	CreatedAt   time.Time `avro:"created_at"`
}

// TaskAssigned is a generated struct.
type TaskAssigned struct {
	Task      Task    `avro:"task"`
	OldUserID *string `avro:"old_user_id"`
}

// TaskCompleted is a generated struct.
type TaskCompleted struct {
	Task Task `avro:"task"`
}

// TransactionCost is a generated struct.
type TransactionCost struct {
	UserID    *string   `avro:"user_id"`
	Source    string    `avro:"source"`
	Cost      int       `avro:"cost"`
	CreatedAt time.Time `avro:"created_at"`
}

// TransactionRevenue is a generated struct.
type TransactionRevenue struct {
	UserID    *string   `avro:"user_id"`
	Source    string    `avro:"source"`
	Revenue   int       `avro:"revenue"`
	CreatedAt time.Time `avro:"created_at"`
}
