package schema_registry

// Code generated by avro/gen. DO NOT EDIT.

import (
	"time"
)

// AccountCreated is a generated struct.
type AccountCreated struct {
	UserID string `avro:"user_id"`
	Role   string `avro:"role"`
}

// AccountUpdated is a generated struct.
type AccountUpdated struct {
	UserID string `avro:"user_id"`
	Active bool   `avro:"active"`
	Role   string `avro:"role"`
}

// EventRaw is a generated struct.
type EventRaw struct {
	EventName     string `avro:"event_name"`
	EventID       string `avro:"event_id"`
	EventVersion  string `avro:"event_version"`
	EventProducer string `avro:"event_producer"`
	Payload       []byte `avro:"payload"`
}

// Meta is a generated struct.
type Meta struct {
	EventName     string `avro:"event_name"`
	EventID       string `avro:"event_id"`
	EventVersion  string `avro:"event_version"`
	EventProducer string `avro:"event_producer"`
}

// Task is a generated struct.
type Task struct {
	TaskID      string    `avro:"task_id"`
	UserID      string    `avro:"user_id"`
	Description string    `avro:"description"`
	Completed   bool      `avro:"completed"`
	CreatedAt   time.Time `avro:"created_at"`
}

// TaskAssigned is a generated struct.
type TaskAssigned struct {
	Task      Task    `avro:"task"`
	OldUserID *string `avro:"old_user_id"`
}

// TaskCompleted is a generated struct.
type TaskCompleted struct {
	Task Task `avro:"task"`
}
