avro:
	avrogen -o schemas/general/generated_schema.go -pkg general schemas/general/*.json
	avrogen -o schemas/v1/generated_schema.go -pkg v1 schemas/v1/*.json
	avrogen -o schemas/v2/generated_schema.go -pkg v2 schemas/v2/*.json
